# Generated by Django 4.1.1 on 2024-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='bank_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='other_deduction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='other_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employees',
            name='acount_number',
            field=models.TextField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='employees',
            name='deduction',
            field=models.FloatField(default=0),
        ),
    ]
