# Generated by Django 3.2.9 on 2024-02-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendace',
            new_name='attendace_info',
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Department_info',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employees_info',
        ),
    ]
