# Generated by Django 4.1.1 on 2024-02-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_info',
            name='Nationality',
            field=models.CharField(choices=[('Saudi', 'Saudi'), ('Non-Sadui', 'Non-Sadui')], default='Saudi', max_length=15, null=True, verbose_name='Nationality'),
        ),
    ]
