# Generated by Django 3.2.9 on 2024-02-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_auto_20240205_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkuser',
            options={},
        ),
    ]
