# Generated by Django 4.1.1 on 2024-02-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
