# Generated by Django 4.1.1 on 2024-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_alter_employees_info_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_info',
            name='Nationality',
            field=models.TextField(null=True),
        ),
    ]
