# Generated by Django 3.2.9 on 2024-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_alter_linkuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_info',
            name='contact',
            field=models.TextField(max_length=10),
        ),
    ]
