# Generated by Django 3.2.9 on 2024-02-07 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_alter_employees_info_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees_info',
            name='contact',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
