# Generated by Django 4.1.1 on 2024-02-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='salary',
            new_name='Basic_salary',
        ),
        migrations.AddField(
            model_name='employees',
            name='Housing_allowance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='other_allowance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='transportation_allowance',
            field=models.FloatField(default=0),
        ),
    ]
