# Generated by Django 4.1.1 on 2024-02-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_alter_employees_info_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=None, help_text='Detction date', null=True, verbose_name='Detction date'),
        ),
    ]
