# Generated by Django 4.1.1 on 2024-02-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_rename_salary_employees_basic_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Basic_salary',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Housing_allowance',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='transportation_allowance',
        ),
    ]
