# Generated by Django 4.1.1 on 2024-02-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
    ]
