# Generated by Django 4.1.1 on 2024-02-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_rename_basic_salary_employees_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='other_deduction',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='other_payment',
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_payment', models.FloatField(default=0)),
                ('other_deduction', models.FloatField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees')),
            ],
        ),
    ]
