# Generated by Django 3.2.9 on 2024-02-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_auto_20240207_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_info',
            name='employeeid',
        ),
    ]
