# Generated by Django 4.1.1 on 2024-02-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0007_remove_employees_other_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='other_deduction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees',
            name='other_payment',
            field=models.FloatField(default=0),
        ),
    ]
