# Generated by Django 4.1.1 on 2024-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_employees_other_deduction_employees_other_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='year_increase',
            field=models.FloatField(default=0),
        ),
    ]
