# Generated by Django 3.2.9 on 2024-02-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_info',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_information.shift'),
            preserve_default=False,
        ),
    ]
