# Generated by Django 3.2.9 on 2024-02-09 19:52

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0012_employees_info_not_paid_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_info',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department_info',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1.1, max_length=63),
            preserve_default=False,
        ),
    ]
