# Generated by Django 3.2.9 on 2024-02-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0013_auto_20240209_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_info',
            name='city',
        ),
    ]
