# Generated by Django 3.2.9 on 2024-02-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0014_remove_department_info_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendace_info',
            name='absent_days',
        ),
        migrations.RemoveField(
            model_name='attendace_info',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='employees_info',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='image',
            field=models.FileField(default='default.png', upload_to='images/'),
        ),
    ]
