# Generated by Django 3.2.9 on 2024-02-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0016_auto_20240212_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_info',
            name='employeeid',
        ),
    ]
