# Generated by Django 3.2.9 on 2024-02-13 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0020_alter_employees_info_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees_info',
            name='employeeid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
