# Generated by Django 3.2.9 on 2024-02-13 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0022_auto_20240213_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees_info',
            name='employeeid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
