# Generated by Django 3.2.9 on 2024-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0024_auto_20240213_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_info',
            name='employeeid',
            field=models.TextField(default=12345),
        ),
    ]
