# Generated by Django 3.2.9 on 2024-02-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0025_alter_employees_info_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_info',
            name='employeeid',
        ),
    ]
