# Generated by Django 3.2.9 on 2024-02-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0033_alter_employees_info_employeeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkuser',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employees_info',
            name='bank_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employees_info',
            name='other_deduction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employees_info',
            name='other_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employees_info',
            name='acount_number',
            field=models.TextField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='employees_info',
            name='deduction',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_payment', models.FloatField(default=0)),
                ('other_deduction', models.FloatField(default=0)),
                ('year_increase', models.FloatField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees_info')),
            ],
        ),
    ]
