# Generated by Django 3.2.9 on 2024-02-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0034_auto_20240217_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkuser',
            options={},
        ),
    ]
