# Generated by Django 3.2.9 on 2024-02-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0035_alter_linkuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkuser',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
