# Generated by Django 3.2.9 on 2024-02-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0036_alter_linkuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkuser',
            options={},
        ),
    ]
