# Generated by Django 3.2.9 on 2024-02-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0038_auto_20240218_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees_info',
            old_name='shift',
            new_name='build',
        ),
    ]
