# Generated by Django 3.2.9 on 2024-02-18 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0039_rename_shift_employees_info_build'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_info',
            name='not_paid_hours',
        ),
    ]
