# Generated by Django 3.2.9 on 2024-02-24 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0042_alter_building_info_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building_info',
            name='location',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[-+]?([0-8]?[0-9]\\.\\d+|[9]0(\\.\\d+)?),[-+]?([0-1][0-7]?[0-9]\\.\\d+|[1]80(\\.\\d+)?)', 'Invalid location format')]),
        ),
    ]
