# Generated by Django 3.2.9 on 2024-02-24 20:04

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0043_alter_building_info_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building_info',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='26.377387, 50.011715', max_length=63),
        ),
    ]
