# Generated by Django 3.2.9 on 2024-02-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0044_alter_building_info_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_info',
            name='Nationality',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pirod',
            name='Employee',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
