# Generated by Django 3.2.9 on 2024-02-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_alter_employees_info_nationality'),
        ('employee_information', '0045_auto_20240225_2329'),
    ]

    operations = [
    ]
