# Generated by Django 4.1.1 on 2024-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approve_by',
            field=models.TextField(default='pending', max_length=100),
        ),
    ]
