# Generated by Django 4.1.1 on 2024-02-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_approve_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='approve_by',
            new_name='Manger_approve_by',
        ),
    ]
