# Generated by Django 4.1.1 on 2024-02-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_rename_approve_by_leave_manger_approve_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
