# Generated by Django 3.2.9 on 2024-02-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20240225_2329'),
        ('leave', '0004_leave_counter_alter_leave_status'),
    ]

    operations = [
    ]
